#vamos ver estruturas de maneiras dinâmicas de ensino a cerca das estruturas e comandos de python
#Version 1.0
import os
def limpa():
    return os.system('cls')
def entrada_saida():
    print("entradas são valores que irão ser atribuídos a elementos chamados variaveis\nusando um comando chamado 'input'\ne para mostrar um texto como esse agora, ou um valor, podemos chamar um comando chamado 'print'")
    ex = input("digite um texto: ")
    limpa()
    print(f"texto digitado: {ex}")
    print("para realizar esta ação anterior, usamos um input, para receber o valor texto digitado por você, e usamos um print para mostrar na tela o que você escreveu.")
    ex = 'texto'
    print(f"Estruturas:\nVariavel = str(input('digite algo: '))\nprint(f,'texto digitado: {ex}')")
    print("IMPORTANTE🚨: o sinal de igual '=' em python não se lê como igual, e sim como recebe, ele é usado para atribuir valores as variaveis, o sinal de igual é representa por dois iguais '=='.")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print(f"maneiras de mostrar textos com valores de variaveis.\nprint(f'texto digitado: {ex}')\nprint('texto digitado: {ex}'.format(texto))\nprint('texto digitado: ',texto)")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
def variaveis():
    print("variaveis são como espaços vazios, que irão receber algum tipo de valor(apenas um), imagime que você tem um guarda roupa, onde você tem uma gaveta que guardas só roupas intimas, você vai e guardar uma cueca preta\né como se você tivesse atribuido um valor a uma variavel chamada gaveta, o valor de 'cueca preta'")
    print("Ex: gaveta = 'cueca preta'\nse você quiser guardar outro tipo de roupa intima, você teria que retirar a cueca preta, pois ela só guarda um valor.")
    print("os tipos primitivos de criação de variaveis são 4:")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("a)int(inteiros): servem para guardar números: 1;2;3 e etc")
    print("b)float(números flutuantes): servem para guardar números com casas decimais ")
    print("c)str(strings): servem para guardar valores textos, qualquer coisa digitado, tem que estar entre aspas, duplas ou solo.")
    print("d)bool(booleanos): servem para receber apenas dois valores(nunca os dois ao mesmo tempo). True/False")
    c = input("digite qualquer cosia para continuar: ")
    limpa()
    print("*Atribuindo diretamente valores as variaveis:\ntexto = 'olá mundo'\n*úsuario atribuindo:\ntexto = str(input('digite algo: '))")
    print("*o comando é dividido em nome da variavel criada, tipo dela, o input para atribuir um valor e um texto dentro do input que irá aparecer para o auxiliar o úsuario")
    print("é importante especificar o tipo da variavel a depender do caso, pois se não especificar, ele irá ler como uma string, e ao fazer calculos, ele irá dar erro.")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("Regras de criações de varaiveis:\nI)elas não podem começar com números\nII)não podem ter simbolos ou acentuações, exceto o '_'\nIII)não podem começar com números\nIV)não podem ser palavras reservas(palavras que já estão sendo usadas no sistema, como print por exemplo)")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
def testes_variaveis():
    print("existe alguns testes que podemos fazer com as variaveis. Como por exemplo:")
    print("a) var.islower(): para saber está em letras minusculas.")
    print("b)Var.isupper(): saber se está em letras maiúsculas.")
    print("c)Var.istitle: saber se as primeiras letras são maiúsculas.")
    print("d)Var.isspace(): se só tem espaços.")
    print("e)Var.isalpha(): se só tem letras.")
    print("f)Var.isnumeric: se só tem números.")
    print("g)Var.isalnum: letras e números, mas qualquer digitação, seja de números ou letras já o fará retornar True")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
def operadores():
    print("os operadores aritmeticos em python são os seguintes: \n(+) soma\n(-) subtração\n(*) multiplicação\n(/) divisão\n(//) divisão inteira(ignora o decimal)\n(%) modulo(resto da divisão)\n(**) potência")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("Exemplos a seguir:")
    print("Ex1: soma = X + Y\nEx2: subtracao = X - Y\nEx3: multiplicacao = X*Y\nEx4: divisao = X/Y\nEx5: divint = X//Y\nEx6: modulo = X%Y\nEx7: potencia = X**Y")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    n1 = 5
    n2 = 2
    print(f"{n1} + {n2} = {n1 + n2} ")
    print(f"{n1} - {n2} = {n1 - n2} ")
    print(f"{n1} / {n2} = {n1 / n2} ")
    print(f"{n1} * {n2} = {n1 * n2} ")
    print(f"{n1} // {n2} = {n1 // n2} ")
    print(f"{n1} % {n2} = {n1 % n2} ")
    print(f"{n1} ** {n2} = {n1 ** n2} ")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("ordem de precedência em uma equação: \n1º parênteses ()\n2º potência\n 3º multiplicação/divisões/modulos\n 4º soma/subtração")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
def biblioteca():
    print("existem coisas chamadas bibliotecas, que seriam como extensções do python para ajudar nossa vida, para fazer algo, com apenas um comando, ao invés de termos de criar linhas de código para aquilo.")
    print("existem bibliotecas integradas no python, mas existem outras que podem ser baixadas e colocadas, basta ter o pip instalado no computador, abrir o prompt de comando, e digite pip install nome_do_pip")
    print("as bibliotecas podem ser importadas de duas maneiras.\nimport biblioteca ou from biblioteca import função_da_biblioteca")
    c = input("digite qualquer coisa para continuar.")
    limpa()
    print("Ex1:\nimport math\nraiz_de_25 = math.sqrt(25) #saída: 5\nEx2: from math import sqrt\nraiz_de_25 = sqrt(25) ")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
def condicao():
     print("se você vai viajar de uma cidade até outra, existem várias opções de caminhos até o destino certo?\nna programação nós podemos prever certos desvios, usando codições.\npor exemplo se eu tiver dinheiro eu compro uma pizza. Se não, eu como um pão.")
     print("isso é também um tipo de condição, na programação temos três condições")
     print("if(se): if condição:")
     print("elif: vem depois do if, para criar outra condiçao.")
     print("else: vem após todos os if presentes na estruturas, para dizer que cada tudo aquilo não seja executado, outra coisa será.")
     c = input("digite qualquer cosia para continuar: ")
     limpa()
     print("Exemplo:\nif nota >= 6:\n   print('aprovado')\nelif nota < 6 and nota >= 4:\n   print('recuperação')\nelse:\n   print(reprovado)")
     c = input("\n\ndigite qualquer coisa para continuar: ")
     limpa()
def repetir():
    print("o nome estruturas de repetições já são autoexplicativos, servem para repetir, enquanto uma condição for atendida.")
    print("imagine que sua mãe diz que você não poderá sair enquanto não arrumar seu quarto, e ela fica indo até seu quarto para conferir, e apenas quando o quarto estiver arrumado, você vai estar liberado.")
    print("exemplo representado em código:")
    print("while arrumar_o_quarto != True:")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("existem dois tipos de estruturas de repetições: while/for")
    print("o while é usado junto a uma condição para que o bloco dentro dele se repita.")
    print("já o for é utilizado com base númerica. Dividido em for, criação de uma variavel in range e valor da variavel criada, até quando irá repetir e o incremento.")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("sintaxe:\na)while (condição):\nb)for variavel in range (valor_variavel,limite,incremento)")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("existem alguns tipos de usos do while e do for, que são interessantes para se trabalhar.")
    print("exemplos de uso do while:\na)while True: serve para loop infinito, sendo quebrado apenas pelo comando break.\nb)while verificação: serve para verificar se o usuário está digitando algo diferente do desejado.")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("existe uma coisa que falaremos no próximo topico, que são as listas, então iremos deixar o exemplos do for para o próximo topico, para explicarmos melhor.")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
def listas():
    print("no topico 2, quando falamos de variaveis, foi dito que as variaveis guardam apenas um valor, pois sempre que atribuido um novo valor a ela, o valor anterior some.")
    print("mas se associarmos uma lista a uma variavel, ela terá mais espaços para guardar elementos.")
    print("é como se no exemplo da cueca preta, agora nós possemos guardar mais cuecas, pois a variavel gaveta agora tem mais espaços para guardar mais cuecas.")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("listas são representadas por: []")
    print("lista pré-definida: lista = [1,2,3]")
    print("listas acionaveis: lista []")
    print("criamos uma lista vazia para que seja adcionado novos elementos a ela, mas também podemos usar uma lista pré-definida e adiconar elementos a ela.")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("manipulações de listas:\na)lista.append(variavel): adcionando elementos a lista.\nb)lista.pop(): exclui o último elemento da lista\nc)lista.remove(elemento): apaga o elemento especifico\nd)del lista: deleta toda a lista")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("Tipos de lista:\na)Tuplas: listas imutaveis quando definidas.\nb)aninhadas: listas dentro de listas, da mesma tipagem. Ex: lista = [[1,2,3],[4,5,6]]\nc)listas compostas: listas dentro de listas com elementos de diferentes tipos. Ex: lista = ['idade',[19]]\nd)Dicionário: listas que definem chaves, a receber respectivos valores, como se você digitasse o nome de alguém, e puxasse todos os dados daquela pessoa.Ex: dict = { 'nome'(chave): 'Gabriel(valor)'")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
def funcao():
    print("funções são como partes resumidas de um código. Servem para ajudar na nossa vida, pois elas nos permitem repetir uma parte do código, se necessário, sem precisar digitar o processo todo de novo, basta chama-la.")
    print("Existem vários tipos de funções, funções ela servem para executar todo um bloco,tanto para retornar valores.")
    print("Existem coisas chamadas parâmetros, que quando queremos retornar um valor, não o deixar apenas dentro da função, precisamos os passar.")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("digamos que A vale 5 e B vale 7.")
    print("ao criar uma função chamada SOMAR_DOIS_NUMEROS e quando eu a chamar, passarei os respectivos valores, e ela irá me retornar a soma entre eles.")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("Exemplo em código:")
    print("def SOMAR_DOIS_NUMEROS(A,B):\n  T = A + B\n  return T")
    c = input("\ndigite qualquer coisa para continuar: ")
    limpa()
    print("existem dois tipos de funções em python, as def e as lambda")
    print("a)def nome_da_função (parâmetros(variaveis criadas para receber valores mostrados antes)):")
    print("b)variavel = lambda variavel:processo a ser feito")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("Exemplos:")
    print("def multiplicacao(X,Y):\n   Total = X*Y\n   return Total\nprint(multiplicacao(5,6)) #saída : 30")
    c = input("\ndigite qualquer coisa para continuar: ")
    limpa()
    print("multiplicacao = lambda x,y: x*y\nprint(multiplicacao(5,6))#saída : 30")
    c = input("\ndigite qualquer coisa para continuar: ")
    limpa()
def erro():
    print("em toda linguagem de programação existem os possiveis erros, onde se o usuário digitar algo diferente do esperado a depender, o programa pode quebrar, além dos erros dentro do próprio código.")
    print("se por exemplo eu colocar para o usuário digitar dois números inteiros para soma-los, e o usuário digitar por exemplo uma letra, o código irá quebrar, mostrando que o usuário digitou algo diferente de um número inteiro.")
    print("em python para evitar que o código quebre, podemos usar um Try para o programa tentar rodar, se ele não conseguir, irá exibir outra coisa.")
    c = input("digite qualquer coisa para continuar: ")
    limpa()
    print("Exemplo:\ntry:\n   n = int(input('digite um número: '))\nexcept Valuerror:\n   print('o que você digitou, não é um número inteiro')")
    c = input("\ndigite qualquer coisa para continuar: ")
    limpa()
    print("existe ainda o comando finally, que é digitado no final do bloco Try/except que ele sempre é executado, independente do erro.")
    c = input("\ndigite qualquer coisa para continuar: ")
    limpa()
    print("Tipos erros para serem utilizados:\na)ValueError: para valores inapropriados para o que queremos.\nb)TypeError: quando uma operação é realizada em um tipo de dado inadequado\nc)IndexError: Ocorre quando você tenta acessar um índice que não existe em uma lista, tupla ou outro tipo de sequência.\nd)KeyError: Ocorre quando você tenta acessar uma chave que não existe em um dicionário.\ne)ZeroDivisionError: Ocorre quando você tenta dividir um número por zero.\nf)FileNotFoundError: ocorre ao tentar abrir um arquivo inexistente.\ng)NameError: ocorre ao tentar acessar uma variavel não criada.\nh)ImportError: quando se tenta importar uma biblioteca que não existe em seu sistema.\ni)OverflowError: ao digitar um número excecivamente grande.\n")
    c = input("\ndigite qualquer coisa para continuar: ")
    limpa()
limpa()
while True:   
    while True:
        parte = input("[1]entradas e saída\n[2]criação de varaiveis/tipos\n[3]testes de variaveis\n[4]operadores aritmeticos e sua ordem de precedência\n[5]bibliotecas\n[6]condições\n[7]repetições\n[8]Listas\n[9]Funções\n[10]tratando erros\n[11]sair\nqual parte você quer aprender agora? ")
        if parte == "1" or parte == "2" or parte == "3" or parte == "4" or parte == "5" or parte == "6" or parte == "7" or parte == "8" or parte == "9" or parte == "10" or  parte == "11":
            limpa()
            break
        limpa()
    if parte == '11':
        break
    match parte:
        case '1':
            entrada_saida()
        case '2':
            variaveis()
        case '3':
            testes_variaveis()
        case '4':
            operadores()
        case '5':
            biblioteca()
        case '6':
           condicao()
        case '7':
            repetir()
        case '8':
            listas()
        case '9':
            funcao() 
        case '10':
            erro()
    resposta = input("deseja continuar (s para sim/n para não)").lower()
    while resposta != "s" and resposta != 'n' :
        limpa()
        resposta = input("deseja continuar (s para sim/n para não)").lower()
    if resposta == 'n':
        limpa()
        break
    limpa()
